const ADMIN_PASSWORD = 'cuorerozzononmente';
const APPROVED_CLANS = ['#GY8VVQC9', '#GLQ8909U', '#QJGQ0UQQ', '#QC8LRJRP', '#GURVCVCU', '#GUR8QRY2'];
const GOOGLE_SHEET_ID = 'INSERISCI_QUI_IL_TUO_GOOGLE_SHEET_ID';
const GOOGLE_API_KEY = 'INSERISCI_QUI_LA_TUA_GOOGLE_API_KEY';
